spring:
  elasticsearch:
    uris: http://elasticsearch-service:9200

  data:
    redis:
      host: redis-service
      port: 6379


minio:
  url: http://minio-service:9000
  bucket:
    name: post-images