spring:
  jwt:
    secret: dklasjdlh21oiio3jk21j3j125h23k1h5l12h45jkndskladajknlfddklad

  datasource:
    username: mysqladmin
    password: mysqladmin

  data:
    redis:
      password: redisadmin

minio:
  access-key: minioadmin
  secret-key: minioadmin