spring:

  datasource:
    url: jdbc:mysql://localhost:33306/personal?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: chat

minio:
  url: http://localhost:9000
  bucket:
    name: post-images

management:
  ## 액추에이터 info 상세 내역
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

  ## 액추에이터 표시할 값들 설정
  endpoint:
    shutdown:
      enabled: true

    caches:
      enabled: false

    ## health 상세 내역 활성화
    health:
      show-details: always
      cache:
        time-to-live: 30s

  ## 액추에이터 web, jmx 설정
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 활성화된 엔드포인트 포함
        exclude: # 개발 환경에서는 모두 노출을 시키지만 배포 환경에서는 예민 정보들을 exclude에 설정한다.
          - threaddump
          - heapdump
    #      base-path: /monitoring
    jmx:
      exposure:
        include: "*"
        exclude:
          - threaddump
          - heapdump
  # 헬스에서 디스크 정보를 삭제
  health:
    diskspace:
      enabled: false


  httpexchanges:
    recording:
      enabled: true